global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Here it's Prometheus itself.
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "webapp"
    metrics_path: '/metrics'
    static_configs:
      - targets: ["mock-coupon-api:8080"]

  - job_name: "loki"
    metrics_path: '/metrics'
    static_configs:
      - targets: ["loki:3100"]
